spring.application.name=Fitness-Monolith

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

spring.app.jwtExpirationMS=7800000
spring.app.jwtSecret=NishanSinghacbdefghijklmnopqrstuvwxyzzxywnshfiehdi

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

#Hibernate creates tables THEN data.sql runs
