spring.application.name=Fitness-Monolith

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.app.jwtExpirationMS=${DATASOURCE_EXPIRATIONS}
spring.app.jwtSecret=${DATASOURCE_SECRET}
spring.app.jwtCookie=${DATASOURCE_COOKIE}

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

#Hibernate creates tables THEN data.sql runs
