spring.application.name=Fitness-Monolith

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.app.jwtExpirationMS=${DATASOURCE_EXPIRATIONS}
spring.app.jwtSecret=${DATASOURCE_SECRET}
spring.app.jwtCookie=${DATASOURCE_COOKIE}


spring.app.adminEmail=${DATASOURCE_adminEmail}
spring.app.adminPassword=${DATASOURCE_adminPassword}
spring.app.adminFirstName=${DATASOURCE_adminFirstName}
spring.app.adminLastName=${DATASOURCE_adminLastName}


spring.app.userEmail=${DATASOURCE_userEmail}
spring.app.userPassword=${DATASOURCE_userPassword}
spring.app.userFirstName=${DATASOURCE_userFirstName}
spring.app.userLastName=${DATASOURCE_userLastName}



spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

#Hibernate creates tables THEN data.sql runs
